extends RefCounted
# Generated by tools/build_midnight_audio.py; original synthesized recordings.
const VARIANTS = {
	"crown":[preload("res://assets/audio/sfx/crown_1.ogg"),preload("res://assets/audio/sfx/crown_2.ogg"),preload("res://assets/audio/sfx/crown_3.ogg")],
	"crown_hit":[preload("res://assets/audio/sfx/crown_hit_1.ogg"),preload("res://assets/audio/sfx/crown_hit_2.ogg"),preload("res://assets/audio/sfx/crown_hit_3.ogg")],
	"catch":[preload("res://assets/audio/sfx/catch_1.ogg"),preload("res://assets/audio/sfx/catch_2.ogg"),preload("res://assets/audio/sfx/catch_3.ogg")],
	"biscuit":[preload("res://assets/audio/sfx/biscuit_1.ogg"),preload("res://assets/audio/sfx/biscuit_2.ogg"),preload("res://assets/audio/sfx/biscuit_3.ogg")],
	"crunch":[preload("res://assets/audio/sfx/crunch_1.ogg"),preload("res://assets/audio/sfx/crunch_2.ogg"),preload("res://assets/audio/sfx/crunch_3.ogg")],
	"throw_die":[preload("res://assets/audio/sfx/throw_die_1.ogg"),preload("res://assets/audio/sfx/throw_die_2.ogg"),preload("res://assets/audio/sfx/throw_die_3.ogg")],
	"clack":[preload("res://assets/audio/sfx/clack_1.ogg"),preload("res://assets/audio/sfx/clack_2.ogg"),preload("res://assets/audio/sfx/clack_3.ogg")],
	"dice":[preload("res://assets/audio/sfx/dice_1.ogg"),preload("res://assets/audio/sfx/dice_2.ogg"),preload("res://assets/audio/sfx/dice_3.ogg")],
	"stamp":[preload("res://assets/audio/sfx/stamp_1.ogg"),preload("res://assets/audio/sfx/stamp_2.ogg"),preload("res://assets/audio/sfx/stamp_3.ogg")],
	"hurt":[preload("res://assets/audio/sfx/hurt_1.ogg")],
	"bomb":[preload("res://assets/audio/sfx/bomb_1.ogg"),preload("res://assets/audio/sfx/bomb_2.ogg"),preload("res://assets/audio/sfx/bomb_3.ogg")],
	"spring":[preload("res://assets/audio/sfx/spring_1.ogg"),preload("res://assets/audio/sfx/spring_2.ogg"),preload("res://assets/audio/sfx/spring_3.ogg")],
	"pickup":[preload("res://assets/audio/sfx/pickup_1.ogg"),preload("res://assets/audio/sfx/pickup_2.ogg"),preload("res://assets/audio/sfx/pickup_3.ogg")],
	"six":[preload("res://assets/audio/sfx/six.ogg")],
	"crumble":[preload("res://assets/audio/sfx/crumble.ogg")],
	"unlock":[preload("res://assets/audio/sfx/unlock.ogg")],
	"arrival":[preload("res://assets/audio/sfx/arrival.ogg")],
	"victory":[preload("res://assets/audio/sfx/victory.ogg")],
}
const MUSIC = [
	preload("res://assets/audio/music/royal_clockwork.ogg"),
	preload("res://assets/audio/music/paperwork_pursuit.ogg"),
	preload("res://assets/audio/music/the_final_audit.ogg"),
]
